import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import streamlit as st
from sql_query_generation import generate_sql_query, run_sql_query

class ExecutiveSummaryVisualization:

    def plot_publisher_revenue(self):
        """Create a bar chart showing total revenue by publisher"""
        publisher_revenue_query = """
            I want you to find the total revenue generated by each publisher and sort them by revenue.
            Resultant columns name should be
                -   PUBLISHER
                -   TOTAL_REVENUE
        """
        query = generate_sql_query(publisher_revenue_query)
        rows = run_sql_query(query)
        revenue_by_publisher = pd.DataFrame(rows)

        fig = px.bar(
            revenue_by_publisher,
            x='PUBLISHER',
            y='TOTAL_REVENUE',
            title='Total Revenue by Publisher',
            labels={'REVENUE': 'Total Revenue ($)', 'PUBLISHER': 'Publisher'},
            color='TOTAL_REVENUE',
            color_continuous_scale='Viridis'
        )
        fig.update_layout(
            xaxis_tickangle=-45,
            showlegend=False,
            height=500
        )
        return fig

    def plot_billable_analysis(self):
        """
        Analyze billable/non-billable leads by publisher with quality threshold
        Returns two plots: percentage and count visualizations
        """
        billable_analysis_query = """
            I want to analyze the billable status of leads by publisher. 
            Please show me for each publisher:
                1. The count of leads
                2. The percentage of leads that are billable vs non-billable
                3. Grouped by publisher and billable status
                4. With percentages calculated as a portion of each publisher's total leads
            OUTPUT COLUMN NAMES:
                - PUBLISHER
                - BILLABLE
                - LEAD COUNT
                - PERCENTAGE
        """
        query = generate_sql_query(billable_analysis_query)
        data = pd.DataFrame(run_sql_query(query))

        # Calculate statistics for summary
        total_leads = data['LEAD COUNT'].sum()
        total_billable = data[data['BILLABLE'] == 'Yes']['LEAD COUNT'].sum()
        overall_billable_rate = (total_billable / total_leads) * 100
        billable_rates = data.pivot(index='PUBLISHER', columns='BILLABLE', values='PERCENTAGE').fillna(0)
        billable_rates['healthy'] = billable_rates['Yes'] >= 70
        problem_publishers = billable_rates[~billable_rates['healthy']].index.tolist()

        st.dataframe(data)

        summary = f"""
            ### Billable Lead Analysis Summary
            
            **Overall Statistics:**
            - 📊 Total leads analyzed: {total_leads:,}
            - ✅ Billable leads: {total_billable:,} ({overall_billable_rate:.1f}%)
            - 🚨 Non-billable leads: {total_leads - total_billable:,} ({100 - overall_billable_rate:.1f}%)
            
            **Publisher Performance:**
            - 🎯 Healthy publishers (≥70% billable): {len(billable_rates[billable_rates['healthy']])}
            - ⚠️ Problem publishers (<70% billable): {len(problem_publishers)}
            {"    - " + ", ".join(problem_publishers) if problem_publishers else "    - All publishers meet quality standards"}
            
            **Key Insights:**
            - The orange dotted line shows our 70% quality threshold
            - Publishers highlighted in red need immediate review
            - Left chart shows percentages - focus on relative performance
            - Right chart shows volumes - identify high-impact issues
        """

        st.markdown(summary)
        
        # Calculate overall billable rate per publisher
        billable_rates = data.pivot(index='PUBLISHER', columns='BILLABLE', values='PERCENTAGE').fillna(0)
        billable_rates['healthy'] = billable_rates['Yes'] >= 70
        
        # Create subplots (1 row, 2 columns)
        fig = make_subplots(
            rows=1, cols=2,
            subplot_titles=(
                'Billable Percentage by Publisher', 
                'Lead Count by Billable Status'
            ),
            horizontal_spacing=0.15
        )
        
        # Percentage Plot (Left)
        for billable_status in ['Yes', 'No']:
            subset = data[data['BILLABLE'] == billable_status]
            fig.add_trace(
                go.Bar(
                    x=subset['PUBLISHER'],
                    y=subset['PERCENTAGE'],
                    name=f'Billable: {billable_status}',
                    marker_color='#2ca02c' if billable_status == 'Yes' else '#d62728',
                    showlegend=True
                ),
                row=1, col=1
            )
        
        # Count Plot (Right)
        for billable_status in ['Yes', 'No']:
            subset = data[data['BILLABLE'] == billable_status]
            fig.add_trace(
                go.Bar(
                    x=subset['PUBLISHER'],
                    y=subset['LEAD COUNT'],
                    name=f'Billable: {billable_status}',
                    marker_color='#2ca02c' if billable_status == 'Yes' else '#d62728',
                    showlegend=False  # Only show legend once
                ),
                row=1, col=2
            )
        
        # Add threshold line to PERCENTAGE plot
        fig.add_hline(
            y=70,
            line_dash="dot",
            annotation_text="70% Threshold",
            line_color="orange",
            row=1, col=1
        )
        
        # Highlight problematic publishers
        for i, publisher in enumerate(billable_rates.index):
            if not billable_rates.loc[publisher, 'healthy']:
                fig.add_vrect(
                    x0=i-0.5, x1=i+0.5,
                    fillcolor="red", opacity=0.1,
                    line_width=0,
                    row=1, col=1
                )
                fig.add_vrect(
                    x0=i-0.5, x1=i+0.5,
                    fillcolor="red", opacity=0.1,
                    line_width=0,
                    row=1, col=2
                )
        
        # Update layout
        fig.update_layout(
            height=500,
            legend_title_text='Billable Status',
            xaxis_tickangle=-45,
            xaxis2_tickangle=-45,
            hovermode='closest',
            margin=dict(l=50, r=50, b=100, t=50, pad=4)
        )
        
        # Update axis labels
        fig.update_yaxes(title_text="Percentage of Leads", row=1, col=1)
        fig.update_yaxes(title_text="Number of Leads", row=1, col=2)
        
        return fig
    
    def plot_ad_misled_analysis(self):
        """
        Analyze misleading ad claims by publisher with compliance alerts
        Returns:
            - fig: Plotly Figure object
            - summary: Markdown formatted compliance summary
        """
        ad_mislead_query = """I need to analyze misleading ad claims by publisher. Please show me for each publisher:
            1. The count of leads labeled as AD_MISLED (both 'Yes' and 'No')
            2. The percentage of leads that have misleading ad claims versus those that don't
            3. Grouped by both publisher and AD_MISLED status
            4. With percentages calculated as a portion of each publisher's total leads

            Make sure to:
            - Only include records where AD_MISLED is not null
            - Name the count column 'LEAD COUNT'
            - Name the percentage column 'PERCENTAGE'
            - Round percentages to 1 decimal place
            - Show results for both 'Yes' and 'No' values of AD_MISLED
        """
        query = generate_sql_query(ad_mislead_query)
        data = pd.DataFrame(run_sql_query(query))
        
        # Calculate statistics for summary
        total_leads = data['LEAD COUNT'].sum()
        total_misled = data[data['AD_MISLED'] == 'Yes']['LEAD COUNT'].sum()
        overall_misled_rate = (total_misled / total_leads) * 100
        misled_rates = data.pivot(index='PUBLISHER', columns='AD_MISLED', values='PERCENTAGE').fillna(0)
        problem_publishers = misled_rates[misled_rates['Yes'] > 0].index.tolist()
        
        st.dataframe(data)

        summary = f"""
            ### Misleading Ad Claims Analysis Summary
            
            **Overall Statistics:**
            - 📊 Total leads analyzed: {total_leads:,}
            - 🚨 Leads with misleading ads: {total_misled:,} ({overall_misled_rate:.1f}%)
            - ✅ Valid ad claims: {total_leads - total_misled:,} ({100 - overall_misled_rate:.1f}%)
            
            **Publisher Performance:**
            - 🎯 Clean publishers (0% misleading): {len(misled_rates[misled_rates['Yes'] == 0])}
            - ⚠️ Publishers with violations: {len(problem_publishers)}
            {"    - " + ", ".join(problem_publishers) if problem_publishers else "    - All publishers have clean records"}
            
            **Compliance Insights:**
            - Any presence of misleading ads requires immediate action
            - Publishers highlighted in red need urgent review
            - Left chart shows percentages - focus on relative impact
            - Right chart shows absolute counts - identify worst offenders
        """

        st.markdown(summary)
        
        # Create subplots (1 row, 2 columns)
        fig = make_subplots(
            rows=1, cols=2,
            subplot_titles=(
                'Misleading Ads Percentage by Publisher', 
                'Misleading Ads Count by Publisher'
            ),
            horizontal_spacing=0.15
        )
        
        # Percentage Plot (Left)
        for misled_status in ['Yes', 'No']:
            subset = data[data['AD_MISLED'] == misled_status]
            fig.add_trace(
                go.Bar(
                    x=subset['PUBLISHER'],
                    y=subset['PERCENTAGE'],
                    name=f'Misleading: {misled_status}',
                    marker_color='#d62728' if misled_status == 'Yes' else '#2ca02c',
                    showlegend=True
                ),
                row=1, col=1
            )
        
        # Count Plot (Right)
        for misled_status in ['Yes', 'No']:
            subset = data[data['AD_MISLED'] == misled_status]
            fig.add_trace(
                go.Bar(
                    x=subset['PUBLISHER'],
                    y=subset['LEAD COUNT'],
                    name=f'Misleading: {misled_status}',
                    marker_color='#d62728' if misled_status == 'Yes' else '#2ca02c',
                    showlegend=False
                ),
                row=1, col=2
            )
        
        # Add zero tolerance line
        fig.add_hline(
            y=0,
            line_dash="dot",
            annotation_text="ZERO TOLERANCE",
            line_color="red",
            row=1, col=1
        )
        
        # Highlight problematic publishers
        for i, publisher in enumerate(misled_rates.index):
            if misled_rates.loc[publisher, 'Yes'] > 0:
                fig.add_vrect(
                    x0=i-0.5, x1=i+0.5,
                    fillcolor="red", opacity=0.1,
                    line_width=0,
                    row=1, col=1
                )
                fig.add_vrect(
                    x0=i-0.5, x1=i+0.5,
                    fillcolor="red", opacity=0.1,
                    line_width=0,
                    row=1, col=2
                )
        
        # Update layout
        fig.update_layout(
            height=500,
            legend_title_text='Misleading Status',
            xaxis_tickangle=-45,
            xaxis2_tickangle=-45,
            hovermode='closest',
            margin=dict(l=50, r=50, b=150, t=50, pad=4),
            annotations=[
                dict(
                    x=0.5,
                    y=-0.25,
                    showarrow=False,
                    text="",
                    xref="paper",
                    yref="paper",
                    font=dict(size=14, color="red")
                )
            ]
        )
        
        # Update axis labels
        fig.update_yaxes(title_text="Percentage of Leads", row=1, col=1)
        fig.update_yaxes(title_text="Number of Leads", row=1, col=2)
        
        return fig

    def plot_reached_agent_analysis(self):
        """
        Analyze agent reach rates by publisher with performance alerts
        Returns:
            - fig: Plotly Figure object
            - summary: Markdown formatted performance summary
        """
        reached_agent_query = """I need to analyze whether leads reached an agent by publisher. Please show me for each publisher:
            1. The count of leads that reached an agent vs those that didn't
            2. The percentage of leads that reached an agent
            3. Grouped by both publisher and REACHED_AGENT status
            4. With percentages calculated as a portion of each publisher's total leads

            Make sure to:
            - Only include records where REACHED_AGENT is not null
            - Name the count column 'LEAD COUNT'
            - Name the percentage column 'PERCENTAGE'
            - Round percentages to 1 decimal place
            - Show results for both 'Yes' and 'No' values of REACHED_AGENT
        """
        query = generate_sql_query(reached_agent_query)
        data = pd.DataFrame(run_sql_query(query))
        
        # Calculate statistics for summary
        total_leads = data['LEAD COUNT'].sum()
        total_reached = data[data['REACHED_AGENT'] == 'Yes']['LEAD COUNT'].sum()
        overall_reach_rate = (total_reached / total_leads) * 100
        reach_rates = data.pivot(index='PUBLISHER', columns='REACHED_AGENT', values='PERCENTAGE').fillna(0)
        reach_rates['healthy'] = reach_rates['Yes'] >= 90  # Critical threshold
        problem_publishers = reach_rates[~reach_rates['healthy']].index.tolist()
        
        st.dataframe(data)

        summary = f"""
            ### Agent Reach Rate Analysis Summary
            
            **Overall Statistics:**
            - 📊 Total leads analyzed: {total_leads:,}
            - ✅ Leads that reached agent: {total_reached:,} ({overall_reach_rate:.1f}%)
            - 🚨 Missed opportunities: {total_leads - total_reached:,} ({100 - overall_reach_rate:.1f}%)
            
            **Publisher Performance:**
            - 🎯 Meeting target (≥90% reach): {len(reach_rates[reach_rates['healthy']])}
            - ⚠️ Below target (<90% reach): {len(problem_publishers)}
            {"    - " + ", ".join(problem_publishers) if problem_publishers else "    - All publishers meet target"}
            
            **Business Impact:**
            - Every missed connection represents potential revenue loss
            - Publishers highlighted in red require immediate capacity review
            - Left chart shows reach percentages - focus on relative performance
            - Right chart shows absolute volumes - identify high-impact issues
        """

        st.markdown(summary)
        
        # Create subplots (1 row, 2 columns)
        fig = make_subplots(
            rows=1, cols=2,
            subplot_titles=(
                'Agent Reach Rate by Publisher (%)', 
                'Lead Volume by Reach Status'
            ),
            horizontal_spacing=0.15
        )
        
        # Percentage Plot (Left)
        for reach_status in ['Yes', 'No']:
            subset = data[data['REACHED_AGENT'] == reach_status]
            fig.add_trace(
                go.Bar(
                    x=subset['PUBLISHER'],
                    y=subset['PERCENTAGE'],
                    name=f'Reached Agent: {reach_status}',
                    marker_color='#2ca02c' if reach_status == 'Yes' else '#d62728',
                    showlegend=True
                ),
                row=1, col=1
            )
        
        # Count Plot (Right)
        for reach_status in ['Yes', 'No']:
            subset = data[data['REACHED_AGENT'] == reach_status]
            fig.add_trace(
                go.Bar(
                    x=subset['PUBLISHER'],
                    y=subset['LEAD COUNT'],
                    name=f'Reached Agent: {reach_status}',
                    marker_color='#2ca02c' if reach_status == 'Yes' else '#d62728',
                    showlegend=False
                ),
                row=1, col=2
            )
        
        # Add critical threshold line (90%)
        fig.add_hline(
            y=90,
            line_dash="dot",
            annotation_text="CRITICAL THRESHOLD (90%)",
            line_color="orange",
            row=1, col=1
        )
        
        # Highlight problematic publishers
        for i, publisher in enumerate(reach_rates.index):
            if not reach_rates.loc[publisher, 'healthy']:
                fig.add_vrect(
                    x0=i-0.5, x1=i+0.5,
                    fillcolor="red", opacity=0.1,
                    line_width=0,
                    row=1, col=1
                )
                fig.add_vrect(
                    x0=i-0.5, x1=i+0.5,
                    fillcolor="red", opacity=0.1,
                    line_width=0,
                    row=1, col=2
                )
        
        # Update layout
        fig.update_layout(
            height=500,
            legend_title_text='Reached Agent?',
            xaxis_tickangle=-45,
            xaxis2_tickangle=-45,
            hovermode='closest',
            margin=dict(l=50, r=50, b=150, t=50, pad=4),
            annotations=[
                dict(
                    x=0.5,
                    y=-0.25,
                    showarrow=False,
                    text="",
                    xref="paper",
                    yref="paper",
                    font=dict(size=14, color="red")
                )
            ]
        )
        
        # Update axis labels
        fig.update_yaxes(title_text="Percentage of Leads", row=1, col=1)
        fig.update_yaxes(title_text="Number of Leads", row=1, col=2)
        
        return fig
    
    def display_all_visualizations(self):
        """Display all visualizations in Streamlit"""
        st.title('Revenue Analysis Dashboard')

        st.header('Publisher Revenue Analysis')
        st.plotly_chart(self.plot_publisher_revenue(), use_container_width=True)

        st.header('Billable Lead Analysis by Publisher')
        st.plotly_chart(self.plot_billable_analysis(), use_container_width=True)

        st.header('Ad Misleading Compliance')
        st.plotly_chart(self.plot_ad_misled_analysis(), use_container_width=True)

        st.header('Agent Reached Analysis')
        st.plotly_chart(self.plot_reached_agent_analysis(), use_container_width=True)
